algorithm: MapElites #MapElites/ NoveltySearch/ CVTMapElites
nb_features: 4
bins_per_dim: 10
nb_bins: [20,5,20,5]
max_items_per_bin: 1                     # The number of items in each bin of the grid
fitness_domain: [[0., 200.]]               # The domain of each fitness objective (here we only have one objective)
features_domain: [[0., 1.], [0., 1.], [0., 1.], [0., 1.]] # The domain of each feature
init_batch_size: 2000
nb_iterations: 1000       # The total number of allowed evaluations for this algorithm
batch_size: 64     # The number of evaluations in each subsequent batch
mutation_pb: 1
final_filename: out/qd_maps/skinner3x10_final.p
#shape: 4096
#####################Encoding parameters###############
encoding: guided-maps #direct/ map-based/ guided-maps
map_size: 3
inner_maps: 10
####################Problem parameters#################
num_episodes: 200
rand_iter: 100
snap_iter: 10
sat_fit: 146
